### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mikeaalv**
The url part and module works for both python 2 and 3. The url part also works for c++

### CODE REVIEW

**Comment by nchernia** [comment]
We don't want to download the whole file.  We need to seek to the appropriate place, like we do in the file.

Check out samtools for an example:

https://github.com/samtools/htslib/blob/develop/hfile_libcurl.c

**Comment by mikeaalv** [comment]
Alright, I will see into it soon

**Comment by nchernia** [comment]
Hello Yue,

Sorry for the long silence.  I've updated the Python version to handle URLs.  I tried to incorporate your changes for the C++ but was unable to get them to work.  

I ran this:

./straw KR https://bcm.box.com/shared/static/48fwiyah1f2qbfabb5bqt1vwwmx06om5.hic 1:1000000:7500000 1:1000000:7500000 BP 25000 > out4.txt

And got this error:
Hi-C magic string is missing, does not appear to be a hic file

This is a proper .hic file, however, and works in both Juicebox tools and the new Python straw.

Let me know if you want to keep working on it, otherwise I will try over the next week.

Best
Neva

**Comment by nchernia** [comment]
Hi Yue

The url is fine - as I said, this example works in the new  Python code. It
also works with Juicebox tools. So I think it's a problem with the code.

Best
Neva

**Comment by mikeaalv** [comment]
If you try download one file using download on the BMC, you will get one url, and I am sure my code works for that url. I didn't try your type of url, because I didn't know it at that time. 
The type of url I have tried is like those in this file https://www.dropbox.com/s/gx15z958kj8t31p/straw_test_CPLUSPLUS.sh?dl=0
These url are get by download the file and will get out of date soon. So, if you want try one, please get a new one yourself. 
I will really appreciate it if you can fix it and tell me what is the problem. 
Thanks a lot
best
Yue Wu

**Comment by sa501428** [comment]
Are you referring to the following url?
https://public.boxcloud.com
/d/1/SqqHVmyQ7Xsw7pGzt50pxAIxLBG-JcrVnebyDpWCeEtGrq6pA32p0K0v5Q7QGmkO6Jzk0Hp4vyD0uSMsfEjMyJ_kZE_0wrCJYBXR_cXOrDyqYAshE6NuoAI4KGgZQkqfmBdK5Ga80t68hdMRPHEwA_053yXvgOlAHXSnw1yo5BHokYFXiTRLF4Sfi4lau4Z36SU3U-d2sG9sQSrIV-vwZM0Fhl4INT1tKCO-bxVV5Aa05ww3LpF1uLJq8Q4zHafthmKBnxdaS_PMD8rtxqw7O_ffVo2ezCDwtJ8bTasPr8ISb4XHpxCUP7tVHoa3xwNYT1WdJj95u84MWXR0RN2ZHcjRgIpJAgO3aaq_oDsUTAxDm1HTcdooRhkdsxgN1iF72TDZjpuUOrUar4yG_J5w4BubAK3lumHFwwhXnxq9th3aKH2P9P1re4-Ai16W9mJ1TBzLDXBkjMXn4CGJWGlbJJOvdncP8-J6e0R2WL2jZMaEkP3lOe9lkJu1QDD28i3If4MZZEG9R5-chYZVsS64GnL3PCdzFyOdTGKM-WY87oEYYd2F1E3Y2ibv4jon-PLpi-EFaguvIiBYXk-iHqiA4Cmew0yaB_O4m2YsYVBebgox-D9oWWN64kO4VyIUXQXRCX-EJVnWWWdz_2SDliCqpdFWMHutOxGoh9B9WxsMcHNGpx_75DPTDmxccNt9exyVx_7-uvTPPxspFEy9it6u24ajsb5-W_JzUkAVYHrlwZAhC7Lsad7Kzj5igKti5vTJ_-rNnRCPhnwZfQBmxZIpMMfJrelbJ4o37XkiucqlFj3_AO6UZW0TFj4DtxBnp16xEsSOWfB80AwQI8NxKCURLZYytNfEvh8k9XJtcAVK_ySa2gUfO1gOWOdS_GJElg5fYCQ6e4gAWyOYGOcOHp8vL5_jC4po3wy3-CSnnYJ3bcssTKNm4ODFR_ni4aj19nIcyZyYuf8rHMZRK1-oMgQ8vAeDx2_L7HLDX-Ng0k_1exnijUrENoiCQNES-ayzPjp8bKeRKUBUJa_YTPGYT4rzSSJbJN0jXfpye9hiBGbuzeOrFgYxci-5udnNTexDsz4YaZ-wX-NWMo64tA
../download

I'm guessing that the hosting on boxcloud uses a different seeking
mechanism. The type we are interested in is the one used by Amazon S3 and
Box.So this would be an ideal link to test with:
https://bcm.box.com/shared/static/48fwiyah1f2qbfabb5bqt1vwwmx06om5.hic
My apologies, I should have clarified this earlier.

Are the python files between the two branches different? And if so, which
are more up-to-date?

- Muhammad Saad Shamim <http://mshamim.com/>

**Comment by nchernia** [comment]
Python: yes and the master is the correct one.

**Comment by mikeaalv** [comment]
Yes, I am using this kind of url and test according to it. I am really sorry for it.
If nchernia is going to fix it next week, I really appreciate the efforts. I am really sorry for it but if there are some other related things to fix and not so urgent, please contact me.
Best.
Yue Wu




At 2017-02-05 03:57:10, "Muhammad Saad Shamim" <notifications@github.com> wrote:
Are you referring to the following url?
https://public.boxcloud.com
/d/1/SqqHVmyQ7Xsw7pGzt50pxAIxLBG-JcrVnebyDpWCeEtGrq6pA32p0K0v5Q7QGmkO6Jzk0Hp4vyD0uSMsfEjMyJ_kZE_0wrCJYBXR_cXOrDyqYAshE6NuoAI4KGgZQkqfmBdK5Ga80t68hdMRPHEwA_053yXvgOlAHXSnw1yo5BHokYFXiTRLF4Sfi4lau4Z36SU3U-d2sG9sQSrIV-vwZM0Fhl4INT1tKCO-bxVV5Aa05ww3LpF1uLJq8Q4zHafthmKBnxdaS_PMD8rtxqw7O_ffVo2ezCDwtJ8bTasPr8ISb4XHpxCUP7tVHoa3xwNYT1WdJj95u84MWXR0RN2ZHcjRgIpJAgO3aaq_oDsUTAxDm1HTcdooRhkdsxgN1iF72TDZjpuUOrUar4yG_J5w4BubAK3lumHFwwhXnxq9th3aKH2P9P1re4-Ai16W9mJ1TBzLDXBkjMXn4CGJWGlbJJOvdncP8-J6e0R2WL2jZMaEkP3lOe9lkJu1QDD28i3If4MZZEG9R5-chYZVsS64GnL3PCdzFyOdTGKM-WY87oEYYd2F1E3Y2ibv4jon-PLpi-EFaguvIiBYXk-iHqiA4Cmew0yaB_O4m2YsYVBebgox-D9oWWN64kO4VyIUXQXRCX-EJVnWWWdz_2SDliCqpdFWMHutOxGoh9B9WxsMcHNGpx_75DPTDmxccNt9exyVx_7-uvTPPxspFEy9it6u24ajsb5-W_JzUkAVYHrlwZAhC7Lsad7Kzj5igKti5vTJ_-rNnRCPhnwZfQBmxZIpMMfJrelbJ4o37XkiucqlFj3_AO6UZW0TFj4DtxBnp16xEsSOWfB80AwQI8NxKCURLZYytNfEvh8k9XJtcAVK_ySa2gUfO1gOWOdS_GJElg5fYCQ6e4gAWyOYGOcOHp8vL5_jC4po3wy3-CSnnYJ3bcssTKNm4ODFR_ni4aj19nIcyZyYuf8rHMZRK1-oMgQ8vAeDx2_L7HLDX-Ng0k_1exnijUrENoiCQNES-ayzPjp8bKeRKUBUJa_YTPGYT4rzSSJbJN0jXfpye9hiBGbuzeOrFgYxci-5udnNTexDsz4YaZ-wX-NWMo64tA
../download

I'm guessing that the hosting on boxcloud uses a different seeking
mechanism. The type we are interested in is the one used by Amazon S3 and
Box.So this would be an ideal link to test with:
https://bcm.box.com/shared/static/48fwiyah1f2qbfabb5bqt1vwwmx06om5.hic
My apologies, I should have clarified this earlier.

Are the python files between the two branches different? And if so, which
are more up-to-date?

- Muhammad Saad Shamim <http://mshamim.com/>

**Pull request closed without merging**
